sudo: false
language: python
addons:
  apt:
    packages:
    - gfortran
cache:
  directories:
  - $HOME/.pip-cache/
matrix:
  include:
  - python: '3.5'
    env: DEPLOY=yes
    os: linux
before_install:
- ./ci/install_gitlfs.sh
- ./ci/install_penelope2014.sh
- pwd
install:
- pip install --cache-dir $HOME/.pip-cache --upgrade pip codecov
- pip install --cache-dir $HOME/.pip-cache --upgrade -r requirements.txt
- python setup.py develop
script:
- nosetests
after_success:
- codecov
notifications:
  email: false

